version: '3.8'

services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat-server
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
